server:
  port: 8001

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kaisheng
    username: root
    password: root
